name: Deploy to AWS ECS

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Snyk Code Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test --all-projects --severity-threshold=high --json-file-output=snyk-code-report.json

      - name: Convert Snyk JSON report to text
        run: |
          jq -r '.vulnerabilities[] | "\(.id): \(.title) - Severity: \(.severity)"' snyk-code-report.json > snyk-code-report.txt || echo "No vulnerabilities found" > snyk-code-report.txt

      - name: Upload Snyk Code Scan report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-code-security-report
          path: snyk-code-report.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push image to Amazon ECR
        env:
          ECR_REPOSITORY: flask-backend
          IMAGE_TAG: latest
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster applicationclusters --service backend-servies --force-new-deployment --desired-count 1 --task-definition backend-td:2
